### ISSUE TITLE
Potential collision in transform-keys function

### ISSUE THREAD

**Issue by tangrammer** [gfredericks/schema-bijections#2]
Hi @gfredericks !
I'm trying to use your lib to have a version of my kebab-case schema in camelCase. But if i use `camel/->camelCase` instead of `camel/->camelCaseString` to have keywords in my camelCase schema as i have in my kebab-case  i got `Potential collision in transform-keys function` error

is it an issue or is there any workaround that?

Thanks in advance for sharing this useful lib!
Juan

**Comment by gfredericks** [comment]
my guess is this is happening because your schema has a `{..., s/Keyword s/Any}` wildcard entry, is that right?

If so, I'm curious what your use for the wildcard is — e.g., are you using schemas that only partially describe the data?

The library is trying to prevent your accidentally clobbering keys that match the wildcard when you transform the normal keys.

**Comment by tangrammer** [comment]
Yes, you're right!
in our app we are in a prototype phase and FrontEnd needs to have this
ignore-data door open, so I had to add this odd piece s/Keyword s/Any to
BackEnd schemas :(
I don't like it but I can't remove it now ...

2016-01-25 17:01 GMT+01:00 Gary Fredericks notifications@github.com:

**Comment by gfredericks** [comment]
my approach to this kind of situation is to strip off extra keys at the boundary, and schema-bijections actually supports this — so with that approach your internal schema would **not** have the wildcard, and you'd use the `allow-extra-keys-on-left` transformer so that your transformed schema **would** have the wildcard and the transformation function would remove the extra keys.

Would that approach work for you?

**Comment by tangrammer** [comment]
Theoretically this approach should work, but the thing is that I don't know how to use `allow-extra-keys-on-left` ... could you provide a minimal example?

**Comment by gfredericks** [comment]
Sure, I just added a test that should help: https://github.com/gfredericks/schema-bijections/blob/29ae297333494853aae04f7cbc4d7012c5e0db74/test/com/gfredericks/schema_bijections_test.clj#L175

**Comment by tangrammer** [comment]
@gfredericks so far is working fine!! give me some time to apply the change and check the results to close the issue but i think I could just say "you save my week, thanks!! " :smile:

**Comment by gfredericks** [comment]
☺

**Comment by tangrammer** [comment]
yeah!
Thanks @gfredericks again!
